Traceback (most recent call last):
  File "mygame.py", line 15, in <module>
  File "C:\Users\ohjunseok\Documents\workspace\myapp\my_app\3차준비프레임워크1 - 복사본\game_framework.py", line 85, in run
    start_state.enter()
  File "C:\Users\ohjunseok\Documents\workspace\myapp\my_app\3차준비프레임워크1 - 복사본\start_state.py", line 13, in enter
    image = load_image('./resource/kpu_credit.png')
  File "C:\Python34\lib\site-packages\pico2d.py", line 268, in load_image
    raise IOError
OSError
